### ISSUE TITLE
Tile description pane not working with less-than-full settings

### ISSUE THREAD

**Issue by AnneTrue** [AnneTrue/libConglomerate#16]
Per Sac: https://www.nexusclash.com/modules.php?name=Forums&file=viewtopic&p=90236#90236

> Bug: Text highlighting indicating the presence of shadows at night (bold red) and lights being on (blue) is not highlighted
> System: Firefox 69.0.1 (64-bit), Tampermonkey 4.9.5941
> Workaround: Both work if "Display Pick-Up Item Count" is also selected on.

It's possibly already fixed in the 4.0 refactor.

**Comment by Bally001** [comment]
No worries.  Just thought I'd try and provide a solution/workaround for a change instead of just highlighting problems ;)
Thanks for your continued work.

**Comment by AnneTrue** [comment]
Thanks for the report, I'm tracking it here so that next time I have free time I can follow up on it and make sure it's fixed in 4.0 and fix it for LibC 3.x in the meantime. :)

Waiting for the 4.0 refactor is nice and all, but that sounds suspiciously like a multi-year wait for version 4 we're well-acquainted with.
