### ISSUE TITLE
ComponenthHighlighting in the safe drop down not working.

### ISSUE THREAD

**Issue by plscks** [AnneTrue/libConglomerate#4]
When options to highlight safe component rarity are selected, the safe item list has nothing highlighted. 

Also, thanks for this thing, it is the best script ever!

![libcbug](https://user-images.githubusercontent.com/7219922/48945935-b66e2180-eef1-11e8-9ad6-c4dcb6f9fea5.png)

**Comment by AnneTrue** [comment]
Thanks for the report! I just saw this after adding the fix. The advanced faction safe was a recent addition to the game.
Issue resolved as of 3.1.3
